name: CI

on:
  pull_request:
  push:
    branches: [ main, feat/2.0.0 ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version-file: '.ruby-version'
          bundler-cache: true

      - name: Test static build
        run: bundle exec ruby bin/build
